# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d83d67e965a21d27825be58e4f456400f968450fabfdaccecacf73d78229bebb005ddb9cac43ef440da1999ab156fb63bb018eb406ec322556f9ac429c303452

test:
  secret_key_base: 19ece26161a76122a34602bce0656f60f73eaaad536546dba3e0ef92882b49a416e2f9c42140d725126cf901957c2b95109eb698f0a7d4d643124b6ef32b8a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
